export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const START_ROUTER_TRANSITION = "START_ROUTER_TRANSITION";
export const END_ROUTER_TRANSITION = "END_ROUTER_TRANSITION";

export const CLEAR_ALERT = "CLEAR_ALERT";

export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";

export const OPEN_REVIEW_MODAL = "OPEN_REVIEW_MODAL";
export const CLOSE_REVIEW_MODAL = "CLOSE_REVIEW_MODAL";

export const HANDLE_QUERY_CHANGE = "HANDLE_QUERY_CHANGE";
export const CLEAR_QUERY_PARAMS = "CLEAR_QUERY_PARAMS";

export const FORCE_REFRESH = "FORCE_REFRESH";

export const REGISTER_USER_RESPONSE = "REGISTER_USER_RESPONSE";

export const LOGIN_USER_RESPONSE = "LOGIN_USER_RESPONSE";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_RESPONSE = "UPDATE_USER_RESPONSE";

export const UPDATE_USER_PASSWORD_RESPONSE = "UPDATE_USER_PASSWORD_RESPONSE";

export const UPDATE_USER_ADDRESS_RESPONSE = "UPDATE_USER_ADDRESS_RESPONSE";

export const USER_REVIEW_RESPONSE = "USER_REVIEW_RESPONSE";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_ERROR = "UPDATE_CART_ERROR";

export const DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS";
export const DELETE_FROM_CART_ERROR = "DELETE_FROM_CART_ERROR";

export const GET_ALL_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

export const GET_FEATURED_PRODUCTS_SUCCESS = "GET_FEATURED_PRODUCTS_SUCCESS";
export const GET_FEATURED_PRODUCTS_ERROR = "GET_FEATURED_PRODUCTS_ERROR";

export const GET_ALL_USER_ORDERS_SUCCESS = "GET_ALL_USER_ORDERS_SUCCESS";
export const GET_ALL_USER_ORDERS_ERROR = "GET_ALL_USER_ORDERS_ERROR";

export const GET_ALL_USER_REVIEWS_SUCCESS = "GET_ALL_USER_REVIEWS_SUCCESS";
export const GET_ALL_USER_REVIEWS_ERROR = "GET_ALL_USER_REVIEWS_ERROR";
