const shippingRates = {
  USA: {
    Alabama: 25,
    Alaska: 40,
    Arizona: 19,
    Arkansas: 21,
    California: 10,
    Colorado: 35,
    Connecticut: 20,
    Delaware: 31,
    Florida: 24,
    Georgia: 10,
    Hawaii: 45,
    Idaho: 23,
    Illinois: 27,
    Indiana: 20,
    Iowa: 22,
    Kansas: 20,
    Kentucky: 25,
    Louisiana: 30,
    Maine: 18,
    Maryland: 10,
    Massachusetts: 20,
    Michigan: 17,
    Minnesota: 25,
    Mississippi: 20,
    Missouri: 16,
    Montana: 29,
    Nebraska: 20,
    Nevada: 28,
    "New Hampshire": 24,
    "New Jersey": 20,
    "New Mexico": 10,
    "New York": 15,
    "North Carolina": 20,
    "North Dakota": 10,
    Ohio: 17,
    Oklahoma: 21,
    Oregon: 20,
    Pennsylvania: 35,
    "Rhode Island": 18,
    "South Carolina": 25,
    "South Dakota": 27,
    Tennessee: 13,
    Texas: 13,
    Utah: 32,
    Vermont: 20,
    Virginia: 29,
    Washington: 10,
    "West Virginia": 20,
    Wisconsin: 30,
    Wyoming: 12,
  },
};
export { shippingRates };
